//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.06 at 11:17:30 AM CEST 
//


package benutzer;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Benutzer" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Benutzername" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Passwort" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Vorname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="EMail">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Anmeldedatum" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="Adresse">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Strasse" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Hausnummer" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="PLZ" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="Ort" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="AnzahlSchnaeppchen" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="GemeldeteSchnaeppchen">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Schnaeppchen" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Bewertung" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "benutzer"
})
@XmlRootElement(name = "Benutzerprofile")
public class Benutzerprofile {

    @XmlElement(name = "Benutzer", required = true)
    protected List<Benutzerprofile.Benutzer> benutzer;

    /**
     * Gets the value of the benutzer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the benutzer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBenutzer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Benutzerprofile.Benutzer }
     * 
     * 
     */
    public List<Benutzerprofile.Benutzer> getBenutzer() {
        if (benutzer == null) {
            benutzer = new ArrayList<Benutzerprofile.Benutzer>();
        }
        return this.benutzer;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Benutzername" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Passwort" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Vorname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="EMail">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Anmeldedatum" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="Adresse">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Strasse" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Hausnummer" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="PLZ" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="Ort" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="AnzahlSchnaeppchen" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="GemeldeteSchnaeppchen">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Schnaeppchen" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Bewertung" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "benutzername",
        "passwort",
        "name",
        "vorname",
        "eMail",
        "anmeldedatum",
        "adresse",
        "anzahlSchnaeppchen",
        "gemeldeteSchnaeppchen",
        "bewertung"
    })
    public static class Benutzer {

        @XmlElement(name = "Id")
        protected int id;
        @XmlElement(name = "Benutzername", required = true)
        protected String benutzername;
        @XmlElement(name = "Passwort", required = true)
        protected String passwort;
        @XmlElement(name = "Name", required = true)
        protected String name;
        @XmlElement(name = "Vorname", required = true)
        protected String vorname;
        @XmlElement(name = "EMail", required = true)
        protected String eMail;
        @XmlElement(name = "Anmeldedatum", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar anmeldedatum;
        @XmlElement(name = "Adresse", required = true)
        protected Benutzerprofile.Benutzer.Adresse adresse;
        @XmlElement(name = "AnzahlSchnaeppchen")
        protected int anzahlSchnaeppchen;
        @XmlElement(name = "GemeldeteSchnaeppchen", required = true)
        protected Benutzerprofile.Benutzer.GemeldeteSchnaeppchen gemeldeteSchnaeppchen;
        @XmlElement(name = "Bewertung", required = true)
        protected String bewertung;

        /**
         * Gets the value of the id property.
         * 
         */
        public int getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(int value) {
            this.id = value;
        }

        /**
         * Gets the value of the benutzername property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBenutzername() {
            return benutzername;
        }

        /**
         * Sets the value of the benutzername property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBenutzername(String value) {
            this.benutzername = value;
        }

        /**
         * Gets the value of the passwort property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPasswort() {
            return passwort;
        }

        /**
         * Sets the value of the passwort property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPasswort(String value) {
            this.passwort = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the vorname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVorname() {
            return vorname;
        }

        /**
         * Sets the value of the vorname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVorname(String value) {
            this.vorname = value;
        }

        /**
         * Gets the value of the eMail property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEMail() {
            return eMail;
        }

        /**
         * Sets the value of the eMail property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEMail(String value) {
            this.eMail = value;
        }

        /**
         * Gets the value of the anmeldedatum property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getAnmeldedatum() {
            return anmeldedatum;
        }

        /**
         * Sets the value of the anmeldedatum property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setAnmeldedatum(XMLGregorianCalendar value) {
            this.anmeldedatum = value;
        }

        /**
         * Gets the value of the adresse property.
         * 
         * @return
         *     possible object is
         *     {@link Benutzerprofile.Benutzer.Adresse }
         *     
         */
        public Benutzerprofile.Benutzer.Adresse getAdresse() {
            return adresse;
        }

        /**
         * Sets the value of the adresse property.
         * 
         * @param value
         *     allowed object is
         *     {@link Benutzerprofile.Benutzer.Adresse }
         *     
         */
        public void setAdresse(Benutzerprofile.Benutzer.Adresse value) {
            this.adresse = value;
        }

        /**
         * Gets the value of the anzahlSchnaeppchen property.
         * 
         */
        public int getAnzahlSchnaeppchen() {
            return anzahlSchnaeppchen;
        }

        /**
         * Sets the value of the anzahlSchnaeppchen property.
         * 
         */
        public void setAnzahlSchnaeppchen(int value) {
            this.anzahlSchnaeppchen = value;
        }

        /**
         * Gets the value of the gemeldeteSchnaeppchen property.
         * 
         * @return
         *     possible object is
         *     {@link Benutzerprofile.Benutzer.GemeldeteSchnaeppchen }
         *     
         */
        public Benutzerprofile.Benutzer.GemeldeteSchnaeppchen getGemeldeteSchnaeppchen() {
            return gemeldeteSchnaeppchen;
        }

        /**
         * Sets the value of the gemeldeteSchnaeppchen property.
         * 
         * @param value
         *     allowed object is
         *     {@link Benutzerprofile.Benutzer.GemeldeteSchnaeppchen }
         *     
         */
        public void setGemeldeteSchnaeppchen(Benutzerprofile.Benutzer.GemeldeteSchnaeppchen value) {
            this.gemeldeteSchnaeppchen = value;
        }

        /**
         * Gets the value of the bewertung property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBewertung() {
            return bewertung;
        }

        /**
         * Sets the value of the bewertung property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBewertung(String value) {
            this.bewertung = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Strasse" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Hausnummer" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="PLZ" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="Ort" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "strasse",
            "hausnummer",
            "plz",
            "ort"
        })
        public static class Adresse {

            @XmlElement(name = "Strasse", required = true)
            protected String strasse;
            @XmlElement(name = "Hausnummer")
            protected int hausnummer;
            @XmlElement(name = "PLZ")
            protected int plz;
            @XmlElement(name = "Ort", required = true)
            protected String ort;

            /**
             * Gets the value of the strasse property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStrasse() {
                return strasse;
            }

            /**
             * Sets the value of the strasse property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStrasse(String value) {
                this.strasse = value;
            }

            /**
             * Gets the value of the hausnummer property.
             * 
             */
            public int getHausnummer() {
                return hausnummer;
            }

            /**
             * Sets the value of the hausnummer property.
             * 
             */
            public void setHausnummer(int value) {
                this.hausnummer = value;
            }

            /**
             * Gets the value of the plz property.
             * 
             */
            public int getPLZ() {
                return plz;
            }

            /**
             * Sets the value of the plz property.
             * 
             */
            public void setPLZ(int value) {
                this.plz = value;
            }

            /**
             * Gets the value of the ort property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrt() {
                return ort;
            }

            /**
             * Sets the value of the ort property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrt(String value) {
                this.ort = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Schnaeppchen" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "schnaeppchen"
        })
        public static class GemeldeteSchnaeppchen {

            @XmlElement(name = "Schnaeppchen", type = Integer.class)
            protected List<Integer> schnaeppchen;

            /**
             * Gets the value of the schnaeppchen property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the schnaeppchen property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSchnaeppchen().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Integer }
             * 
             * 
             */
            public List<Integer> getSchnaeppchen() {
                if (schnaeppchen == null) {
                    schnaeppchen = new ArrayList<Integer>();
                }
                return this.schnaeppchen;
            }

        }

    }

}
