//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.11 at 06:23:41 PM CEST 
//


package benutzer;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.example.benutzer package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.example.benutzer
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Benutzerprofile }
     * 
     */
    public Benutzerprofile createBenutzerprofile() {
        return new Benutzerprofile();
    }

    /**
     * Create an instance of {@link Benutzerprofile.Benutzer }
     * 
     */
    public Benutzerprofile.Benutzer createBenutzerprofileBenutzer() {
        return new Benutzerprofile.Benutzer();
    }

    /**
     * Create an instance of {@link Benutzerprofile.Benutzer.Adresse }
     * 
     */
    public Benutzerprofile.Benutzer.Adresse createBenutzerprofileBenutzerAdresse() {
        return new Benutzerprofile.Benutzer.Adresse();
    }

    /**
     * Create an instance of {@link Benutzerprofile.Benutzer.GemeldeteSchnaeppchen }
     * 
     */
    public Benutzerprofile.Benutzer.GemeldeteSchnaeppchen createBenutzerprofileBenutzerGemeldeteSchnaeppchen() {
        return new Benutzerprofile.Benutzer.GemeldeteSchnaeppchen();
    }

}
