//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.06 at 11:17:41 AM CEST 
//


package org.example.maerkte;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Kette" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Markt" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="Adresse" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Strasse" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Hausnummer" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="PLZ" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="Ort" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Schnaeppchenxyz">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Schnaeppchen" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "kette"
})
@XmlRootElement(name = "Maerkte")
public class Maerkte {

    @XmlElement(name = "Kette", required = true)
    protected List<Maerkte.Kette> kette;

    /**
     * Gets the value of the kette property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kette property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKette().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Maerkte.Kette }
     * 
     * 
     */
    public List<Maerkte.Kette> getKette() {
        if (kette == null) {
            kette = new ArrayList<Maerkte.Kette>();
        }
        return this.kette;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Markt" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="Adresse" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Strasse" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Hausnummer" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="PLZ" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="Ort" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Schnaeppchenxyz">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Schnaeppchen" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "markt"
    })
    public static class Kette {

        @XmlElement(name = "Name", required = true)
        protected String name;
        @XmlElement(name = "Markt", required = true)
        protected List<Maerkte.Kette.Markt> markt;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the markt property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the markt property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMarkt().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Maerkte.Kette.Markt }
         * 
         * 
         */
        public List<Maerkte.Kette.Markt> getMarkt() {
            if (markt == null) {
                markt = new ArrayList<Maerkte.Kette.Markt>();
            }
            return this.markt;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="Adresse" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Strasse" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Hausnummer" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="PLZ" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="Ort" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Schnaeppchenxyz">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Schnaeppchen" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "adresse",
            "schnaeppchenxyz"
        })
        public static class Markt {

            @XmlElement(name = "Id")
            protected int id;
            @XmlElement(name = "Adresse")
            protected Maerkte.Kette.Markt.Adresse adresse;
            @XmlElement(name = "Schnaeppchenxyz", required = true)
            protected Maerkte.Kette.Markt.Schnaeppchenxyz schnaeppchenxyz;

            /**
             * Gets the value of the id property.
             * 
             */
            public int getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(int value) {
                this.id = value;
            }

            /**
             * Gets the value of the adresse property.
             * 
             * @return
             *     possible object is
             *     {@link Maerkte.Kette.Markt.Adresse }
             *     
             */
            public Maerkte.Kette.Markt.Adresse getAdresse() {
                return adresse;
            }

            /**
             * Sets the value of the adresse property.
             * 
             * @param value
             *     allowed object is
             *     {@link Maerkte.Kette.Markt.Adresse }
             *     
             */
            public void setAdresse(Maerkte.Kette.Markt.Adresse value) {
                this.adresse = value;
            }

            /**
             * Gets the value of the schnaeppchenxyz property.
             * 
             * @return
             *     possible object is
             *     {@link Maerkte.Kette.Markt.Schnaeppchenxyz }
             *     
             */
            public Maerkte.Kette.Markt.Schnaeppchenxyz getSchnaeppchenxyz() {
                return schnaeppchenxyz;
            }

            /**
             * Sets the value of the schnaeppchenxyz property.
             * 
             * @param value
             *     allowed object is
             *     {@link Maerkte.Kette.Markt.Schnaeppchenxyz }
             *     
             */
            public void setSchnaeppchenxyz(Maerkte.Kette.Markt.Schnaeppchenxyz value) {
                this.schnaeppchenxyz = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Strasse" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Hausnummer" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="PLZ" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="Ort" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "strasse",
                "hausnummer",
                "plz",
                "ort"
            })
            public static class Adresse {

                @XmlElement(name = "Strasse", required = true)
                protected String strasse;
                @XmlElement(name = "Hausnummer")
                protected int hausnummer;
                @XmlElement(name = "PLZ")
                protected int plz;
                @XmlElement(name = "Ort", required = true)
                protected String ort;

                /**
                 * Gets the value of the strasse property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStrasse() {
                    return strasse;
                }

                /**
                 * Sets the value of the strasse property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStrasse(String value) {
                    this.strasse = value;
                }

                /**
                 * Gets the value of the hausnummer property.
                 * 
                 */
                public int getHausnummer() {
                    return hausnummer;
                }

                /**
                 * Sets the value of the hausnummer property.
                 * 
                 */
                public void setHausnummer(int value) {
                    this.hausnummer = value;
                }

                /**
                 * Gets the value of the plz property.
                 * 
                 */
                public int getPLZ() {
                    return plz;
                }

                /**
                 * Sets the value of the plz property.
                 * 
                 */
                public void setPLZ(int value) {
                    this.plz = value;
                }

                /**
                 * Gets the value of the ort property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOrt() {
                    return ort;
                }

                /**
                 * Sets the value of the ort property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOrt(String value) {
                    this.ort = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Schnaeppchen" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "schnaeppchen"
            })
            public static class Schnaeppchenxyz {

                @XmlElement(name = "Schnaeppchen", type = Integer.class)
                protected List<Integer> schnaeppchen;

                /**
                 * Gets the value of the schnaeppchen property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the schnaeppchen property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getSchnaeppchen().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Integer }
                 * 
                 * 
                 */
                public List<Integer> getSchnaeppchen() {
                    if (schnaeppchen == null) {
                        schnaeppchen = new ArrayList<Integer>();
                    }
                    return this.schnaeppchen;
                }

            }

        }

    }

}
