//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.06 at 11:17:30 AM CEST 
//


package org.example.schnaeppchen;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.example.schnaeppchen package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.example.schnaeppchen
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Schnaeppchenxyz }
     * 
     */
    public Schnaeppchenxyz createSchnaeppchenxyz() {
        return new Schnaeppchenxyz();
    }

    /**
     * Create an instance of {@link Schnaeppchenxyz.Schnaeppchen }
     * 
     */
    public Schnaeppchenxyz.Schnaeppchen createSchnaeppchenxyzSchnaeppchen() {
        return new Schnaeppchenxyz.Schnaeppchen();
    }

    /**
     * Create an instance of {@link Schnaeppchenxyz.Schnaeppchen.Kommentare }
     * 
     */
    public Schnaeppchenxyz.Schnaeppchen.Kommentare createSchnaeppchenxyzSchnaeppchenKommentare() {
        return new Schnaeppchenxyz.Schnaeppchen.Kommentare();
    }

    /**
     * Create an instance of {@link Schnaeppchenxyz.Schnaeppchen.Preise }
     * 
     */
    public Schnaeppchenxyz.Schnaeppchen.Preise createSchnaeppchenxyzSchnaeppchenPreise() {
        return new Schnaeppchenxyz.Schnaeppchen.Preise();
    }

    /**
     * Create an instance of {@link Schnaeppchenxyz.Schnaeppchen.Datum }
     * 
     */
    public Schnaeppchenxyz.Schnaeppchen.Datum createSchnaeppchenxyzSchnaeppchenDatum() {
        return new Schnaeppchenxyz.Schnaeppchen.Datum();
    }

    /**
     * Create an instance of {@link Schnaeppchenxyz.Schnaeppchen.Kommentare.Kommentar }
     * 
     */
    public Schnaeppchenxyz.Schnaeppchen.Kommentare.Kommentar createSchnaeppchenxyzSchnaeppchenKommentareKommentar() {
        return new Schnaeppchenxyz.Schnaeppchen.Kommentare.Kommentar();
    }

}
