//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.11 at 06:23:41 PM CEST 
//


package schnaeppchen;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Schnaeppchen" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Titel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Benutzer" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Kategorie">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Elektronik"/>
 *                         &lt;enumeration value="Kategorie2"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Bild" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *                   &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *                   &lt;element name="Markt" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
 *                   &lt;element name="Preise">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Preis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="UVP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="Waehrung">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="Euro"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Datum">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Tag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Uhrzeit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Kommentare" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Kommentar" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="Autor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="Datum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="Uhrzeit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "schnaeppchen"
})
@XmlRootElement(name = "Schnaeppchenxyz")
public class Schnaeppchenxyz {

    @XmlElement(name = "Schnaeppchen", required = true)
    protected List<Schnaeppchenxyz.Schnaeppchen> schnaeppchen;

    /**
     * Gets the value of the schnaeppchen property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the schnaeppchen property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSchnaeppchen().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Schnaeppchenxyz.Schnaeppchen }
     * 
     * 
     */
    public List<Schnaeppchenxyz.Schnaeppchen> getSchnaeppchen() {
        if (schnaeppchen == null) {
            schnaeppchen = new ArrayList<Schnaeppchenxyz.Schnaeppchen>();
        }
        return this.schnaeppchen;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Titel" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Benutzer" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Kategorie">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Elektronik"/>
     *               &lt;enumeration value="Kategorie2"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Bild" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
     *         &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
     *         &lt;element name="Markt" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
     *         &lt;element name="Preise">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Preis" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="UVP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="Waehrung">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="Euro"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Datum">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Tag" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Uhrzeit" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Kommentare" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Kommentar" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="Autor" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="Datum" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="Uhrzeit" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "titel",
        "benutzer",
        "kategorie",
        "bild",
        "url",
        "markt",
        "preise",
        "text",
        "datum",
        "kommentare"
    })
    public static class Schnaeppchen {

        @XmlElement(name = "ID")
        protected int id;
        @XmlElement(name = "Titel", required = true)
        protected String titel;
        @XmlElement(name = "Benutzer")
        protected int benutzer;
        @XmlElement(name = "Kategorie", required = true)
        protected String kategorie;
        @XmlElement(name = "Bild")
        @XmlSchemaType(name = "anyURI")
        protected String bild;
        @XmlElement(name = "URL")
        @XmlSchemaType(name = "anyURI")
        protected String url;
        @XmlElement(name = "Markt", type = Integer.class)
        protected List<Integer> markt;
        @XmlElement(name = "Preise", required = true)
        protected Schnaeppchenxyz.Schnaeppchen.Preise preise;
        @XmlElement(name = "Text", required = true)
        protected String text;
        @XmlElement(name = "Datum", required = true)
        protected Schnaeppchenxyz.Schnaeppchen.Datum datum;
        @XmlElement(name = "Kommentare")
        protected Schnaeppchenxyz.Schnaeppchen.Kommentare kommentare;

        /**
         * Gets the value of the id property.
         * 
         */
        public int getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setID(int value) {
            this.id = value;
        }

        /**
         * Gets the value of the titel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitel() {
            return titel;
        }

        /**
         * Sets the value of the titel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitel(String value) {
            this.titel = value;
        }

        /**
         * Gets the value of the benutzer property.
         * 
         */
        public int getBenutzer() {
            return benutzer;
        }

        /**
         * Sets the value of the benutzer property.
         * 
         */
        public void setBenutzer(int value) {
            this.benutzer = value;
        }

        /**
         * Gets the value of the kategorie property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKategorie() {
            return kategorie;
        }

        /**
         * Sets the value of the kategorie property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKategorie(String value) {
            this.kategorie = value;
        }

        /**
         * Gets the value of the bild property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBild() {
            return bild;
        }

        /**
         * Sets the value of the bild property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBild(String value) {
            this.bild = value;
        }

        /**
         * Gets the value of the url property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getURL() {
            return url;
        }

        /**
         * Sets the value of the url property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setURL(String value) {
            this.url = value;
        }

        /**
         * Gets the value of the markt property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the markt property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMarkt().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getMarkt() {
            if (markt == null) {
                markt = new ArrayList<Integer>();
            }
            return this.markt;
        }

        /**
         * Gets the value of the preise property.
         * 
         * @return
         *     possible object is
         *     {@link Schnaeppchenxyz.Schnaeppchen.Preise }
         *     
         */
        public Schnaeppchenxyz.Schnaeppchen.Preise getPreise() {
            return preise;
        }

        /**
         * Sets the value of the preise property.
         * 
         * @param value
         *     allowed object is
         *     {@link Schnaeppchenxyz.Schnaeppchen.Preise }
         *     
         */
        public void setPreise(Schnaeppchenxyz.Schnaeppchen.Preise value) {
            this.preise = value;
        }

        /**
         * Gets the value of the text property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getText() {
            return text;
        }

        /**
         * Sets the value of the text property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setText(String value) {
            this.text = value;
        }

        /**
         * Gets the value of the datum property.
         * 
         * @return
         *     possible object is
         *     {@link Schnaeppchenxyz.Schnaeppchen.Datum }
         *     
         */
        public Schnaeppchenxyz.Schnaeppchen.Datum getDatum() {
            return datum;
        }

        /**
         * Sets the value of the datum property.
         * 
         * @param value
         *     allowed object is
         *     {@link Schnaeppchenxyz.Schnaeppchen.Datum }
         *     
         */
        public void setDatum(Schnaeppchenxyz.Schnaeppchen.Datum value) {
            this.datum = value;
        }

        /**
         * Gets the value of the kommentare property.
         * 
         * @return
         *     possible object is
         *     {@link Schnaeppchenxyz.Schnaeppchen.Kommentare }
         *     
         */
        public Schnaeppchenxyz.Schnaeppchen.Kommentare getKommentare() {
            return kommentare;
        }

        /**
         * Sets the value of the kommentare property.
         * 
         * @param value
         *     allowed object is
         *     {@link Schnaeppchenxyz.Schnaeppchen.Kommentare }
         *     
         */
        public void setKommentare(Schnaeppchenxyz.Schnaeppchen.Kommentare value) {
            this.kommentare = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Tag" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Uhrzeit" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tag",
            "uhrzeit"
        })
        public static class Datum {

            @XmlElement(name = "Tag", required = true)
            protected String tag;
            @XmlElement(name = "Uhrzeit", required = true)
            protected String uhrzeit;

            /**
             * Gets the value of the tag property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTag() {
                return tag;
            }

            /**
             * Sets the value of the tag property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTag(String value) {
                this.tag = value;
            }

            /**
             * Gets the value of the uhrzeit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUhrzeit() {
                return uhrzeit;
            }

            /**
             * Sets the value of the uhrzeit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUhrzeit(String value) {
                this.uhrzeit = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Kommentar" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="Autor" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="Datum" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="Uhrzeit" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "kommentar"
        })
        public static class Kommentare {

            @XmlElement(name = "Kommentar")
            protected List<Schnaeppchenxyz.Schnaeppchen.Kommentare.Kommentar> kommentar;

            /**
             * Gets the value of the kommentar property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the kommentar property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getKommentar().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Schnaeppchenxyz.Schnaeppchen.Kommentare.Kommentar }
             * 
             * 
             */
            public List<Schnaeppchenxyz.Schnaeppchen.Kommentare.Kommentar> getKommentar() {
                if (kommentar == null) {
                    kommentar = new ArrayList<Schnaeppchenxyz.Schnaeppchen.Kommentare.Kommentar>();
                }
                return this.kommentar;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *       &lt;attribute name="Autor" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="Datum" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="Uhrzeit" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "text"
            })
            public static class Kommentar {

                @XmlElement(name = "Text", required = true)
                protected String text;
                @XmlAttribute(name = "Autor")
                protected String autor;
                @XmlAttribute(name = "Datum")
                protected String datum;
                @XmlAttribute(name = "Uhrzeit")
                protected String uhrzeit;

                /**
                 * Gets the value of the text property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getText() {
                    return text;
                }

                /**
                 * Sets the value of the text property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setText(String value) {
                    this.text = value;
                }

                /**
                 * Gets the value of the autor property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAutor() {
                    return autor;
                }

                /**
                 * Sets the value of the autor property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAutor(String value) {
                    this.autor = value;
                }

                /**
                 * Gets the value of the datum property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDatum() {
                    return datum;
                }

                /**
                 * Sets the value of the datum property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDatum(String value) {
                    this.datum = value;
                }

                /**
                 * Gets the value of the uhrzeit property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUhrzeit() {
                    return uhrzeit;
                }

                /**
                 * Sets the value of the uhrzeit property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUhrzeit(String value) {
                    this.uhrzeit = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Preis" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="UVP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="Waehrung">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="Euro"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "preis",
            "uvp"
        })
        public static class Preise {

            @XmlElement(name = "Preis", required = true)
            protected String preis;
            @XmlElement(name = "UVP")
            protected String uvp;
            @XmlAttribute(name = "Waehrung")
            protected String waehrung;

            /**
             * Gets the value of the preis property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPreis() {
                return preis;
            }

            /**
             * Sets the value of the preis property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPreis(String value) {
                this.preis = value;
            }

            /**
             * Gets the value of the uvp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUVP() {
                return uvp;
            }

            /**
             * Sets the value of the uvp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUVP(String value) {
                this.uvp = value;
            }

            /**
             * Gets the value of the waehrung property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getWaehrung() {
                return waehrung;
            }

            /**
             * Sets the value of the waehrung property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWaehrung(String value) {
                this.waehrung = value;
            }

        }

    }

}
